### ISSUE TITLE
CoCT stage not matching output

### ISSUE THREAD

**Issue by Sn00zEZA** [tinuva/nodered-coct-loadshedding#1]
Current output is matching Eskom stage and not City of Cape Town stage. 
Eskom currently Stage 5 and CoCT stage 4 but output is for Stage 5 Eskom.

**Comment by tinuva** [comment]
This issue is highly annoying. I don't know of an API endpoint that output the CoCT stage correctly all the time.

**Comment by Sn00zEZA** [comment]
I found this other repo https://github.com/Quantiversal/Cape-Town-Loadshedding-Schedule and the api https://ewn.co.za/assets/loadshedding/api/status
Hope this helps, will you be able to use that for the output?

Also saw that Eskom-sepush api is only available for business :(

**Comment by tinuva** [comment]
This flow actually used the code from https://github.com/Quantiversal/Cape-Town-Loadshedding-Schedule  for the schedule already. The ewn api however is slow to get updated but we can look at it. Also the wording is not always the same so extracting the CoCT stage is a hit and miss. I am actually looking for a direct CoCT source.

**Comment by tinuva** [comment]
I actually found CoCTs open data website, might work, but need to test while the stages are different again.
```
~ % curl -s 'https://services.esri-southafrica.com/hosting/rest/services/LoadShedding/LoadShedding/FeatureServer/0/query?f=json&geometry=%7B%22xmin%22%3A-0.000004988163709640503%2C%22ymin%22%3A-5009377.08569099%2C%22xmax%22%3A2504688.542843003%2C%22ymax%22%3A-2504688.542843003%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&outFields=*' | jq '.features[0].attributes.Stage_Live'
4
```

More detail:
```
~ % curl -s 'https://services.esri-southafrica.com/hosting/rest/services/LoadShedding/LoadShedding/FeatureServer/0/query?f=json&geometry=%7B%22xmin%22%3A-0.000004988163709640503%2C%22ymin%22%3A-5009377.08569099%2C%22xmax%22%3A2504688.542843003%2C%22ymax%22%3A-2504688.542843003%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&outFields=*' | jq '.features[0].attributes'
{
  "OBJECTID": 222550,
  "BlockID": 1,
  "Shape_Leng": 42603.05821600838,
  "Day": "8",
  "S1": 1581969600000,
  "S2": 1581912000000,
  "S3": null,
  "S4": 1581940800000,
  "Stage_Live": 4
}
```

**Comment by tinuva** [comment]
If you want an accurate stage for CoCT, I found an endpoint that needs more than just scraping.
However I am not using this flow anymore, but instead created a home assistant addon you can install with HACS.
See: https://github.com/tinuva/ha-coct-loadshedding

**Comment by Sn00zEZA** [comment]
Interesting, thank you. Already running a basic HA. Will see if I can setup what I'm trying to do on there.

**Comment by tinuva** [comment]
Look you can still use node-red. Just use the entities from home assistant at the start of your flow. The "event state" node can do this like this:
![Screenshot 2022-07-10 at 19 38 27](https://user-images.githubusercontent.com/5417682/178155842-be749620-ed4c-4ae6-a68f-64f232f2cc56.png)
All this need, is nodered connected to HA.
